# Generated by Django 4.2.3 on 2023-08-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reactpy_django", "0003_componentsession_delete_componentparams"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cleaned_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
