# Generated by Django 4.2.5 on 2023-10-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reactpy_django", "0005_alter_componentsession_last_accessed"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_pk", models.CharField(max_length=255, unique=True)),
                ("data", models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
