# Generated by Django 5.1.4 on 2024-12-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactpy_django', '0006_userdatamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('session_key', models.CharField(editable=False, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
