# Generated by Django 4.2.5 on 2023-09-26 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reactpy_django", "0007_alter_userdatamodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdatamodel",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
