# Generated by Django 5.1.4 on 2026-09-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactpy_django', '0007_authtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionStateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_id', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('data', models.BinaryField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['scope_id', 'updated_at'], name='reactpy_dj_scope_i_1cf868_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sessionstatemodel',
            constraint=models.UniqueConstraint(fields=('scope_id', 'key'), name='reactpy_django_sess_scope_id_key'),
        ),
    ]
