# Generated by Django 5.1.4 on 2024-12-25 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactpy_django', '0008_rename_authsession_switchsession'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SwitchSession',
            new_name='SynchronizeSession',
        ),
    ]
