# Generated by Django 4.2.5 on 2023-09-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reactpy_django", "0008_alter_userdatamodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdatamodel",
            name="data",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
