# Generated by Django 5.1.4 on 2024-12-25 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactpy_django', '0009_rename_switchsession_synchronizesession'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SynchronizeSession',
            new_name='AuthToken',
        ),
        migrations.RenameField(
            model_name='authtoken',
            old_name='uuid',
            new_name='value',
        ),
    ]
