# Generated by Django 4.1.5 on 2023-01-13 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0002_relationalchild_relationalparent_foriegnchild"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foriegnchild",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent",
                to="test_app.relationalparent",
            ),
        ),
        migrations.AlterField(
            model_name="relationalparent",
            name="one_to_one",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="one_to_one",
                to="test_app.relationalchild",
            ),
        ),
    ]
