# Generated by Django 4.1.5 on 2023-01-13 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0004_alter_foriegnchild_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foriegnchild",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="many_to_one",
                to="test_app.relationalparent",
            ),
        ),
    ]
