# Generated by Django 4.1.7 on 2023-03-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0005_alter_foriegnchild_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsyncTodoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("done", models.BooleanField()),
                ("text", models.CharField(max_length=1000)),
            ],
        ),
    ]
