# Generated by Django 4.1.7 on 2023-03-16 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0006_asynctodoitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsyncRelationalChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="AsyncRelationalParent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("done", models.BooleanField(default=True)),
                (
                    "many_to_many",
                    models.ManyToManyField(
                        related_name="many_to_many", to="test_app.asyncrelationalchild"
                    ),
                ),
                (
                    "one_to_one",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="one_to_one",
                        to="test_app.asyncrelationalchild",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AsyncForiegnChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=1000)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="many_to_one",
                        to="test_app.asyncrelationalparent",
                    ),
                ),
            ],
        ),
    ]
