# Generated by Django 4.2.2 on 2023-07-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0007_asyncrelationalchild_asyncrelationalparent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asynctodoitem",
            name="text",
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name="todoitem",
            name="text",
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
