name: Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    javascript:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - uses: actions/setup-python@v5
              with:
                  python-version: 3.x
            - name: Install Python Dependencies
              run: pip install hatch
            - name: Run Tests
              run: hatch run javascript:check
